apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: breast-cancer-knn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Wertyhan/kubeflow-ml-cicd.git
    targetRevision: main
    path: pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
